apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rock-paper-scissors-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/huinno-yoseph/rock-paper-scissors.git'
    targetRevision: HEAD
    path: 'k8s'  # Kubernetes manifests가 있는 디렉터리
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true